### ISSUE TITLE
Turn on autocomplete

### ISSUE THREAD

**Issue by MatthiasPortzel** [CS-Underground/live-editor#1]
Ace and KA support auto completion, but KA turned it off because it was "too confusing." 

It was turned off by Khan/live-editor@4e028ca, and running this on a KA page will turn it on.
```
ScratchpadAutosuggest.editor.setOptions({enableLiveAutocompletion: true}); //Turn it on. You could add other Ace options here too, even without the lower line.
ScratchpadAutosuggest.enableLiveCompletion = (enable => enable); //Overwrite KA's function to keep them from turning it back off
```
From that you should be able to turn it on and keep it on.

Edit: Was fixed by 5cb7a0eab73a6be11a2d7536ec428bffb2610eb3. Is now broken again. :|

**Comment by codeHusky** [comment]
Done.

**Comment by codeHusky** [comment]
Currently disabled as I figure out why resizing is broken.
